# -*- coding utf-8 -*-
"""
Will receive and interpret an abstract syntax tree (generated by the parser)
"""
from __future__ import unicode_literals


def interpret(ast, scope={}):
    """
    :param ast: An abstract syntax tree - generated by the parser
    :param scope: The scope where to interpret the abstract syntax tree
    :return: The value of the evaluation
    """
    if not ast:
        return

    result = None
    for elem in ast:
        if hasattr(elem, 'eval'):
            result = elem.eval(scope)
        # TODO - parser must return only evaluable objects
        else:
            result = elem

    return result
