# -*- coding utf-8 -*-
"""
Will receive and interpret an abstract syntax tree (generated by the parser)
"""

def interpret(ast, scope=None):
    """
    :param ast: An abstract syntax tree - generated by the parser
    :param scope: The scope where to interpret the abstract syntax tree
    :return: The value of the evaluation
    """